import request from './request'

export const getUsersApi = (params) => request.get('/system/users', { params })
export const saveUserApi = (data) => request.post('/system/users', data)
export const deleteUserApi = (id) => request.delete(`/system/users/${id}`)
export const updateUserStatusApi = (id, status) => request.patch(`/system/users/${id}/status`, { status })
export const getRolesApi = (params) => request.get('/system/roles', { params })
export const saveRoleApi = (data) => request.post('/system/roles', data)
export const deleteRoleApi = (id) => request.delete(`/system/roles/${id}`)
export const updateRoleStatusApi = (id, status) => request.patch(`/system/roles/${id}/status`, { status })
export const getMenusApi = (params) => request.get('/system/menus', { params })
export const saveMenuApi = (data) => request.post('/system/menus', data)
export const deleteMenuApi = (id) => request.delete(`/system/menus/${id}`)
export const getPermissionsApi = () => request.get('/system/permissions')
export const savePermissionApi = (data) => request.post('/system/permissions', data)
export const deletePermissionApi = (id) => request.delete(`/system/permissions/${id}`)
export const getLogsApi = (params) => request.get('/system/logs', { params })
export const generateOpenAPIHeadersApi = (data) => request.post('/system/openapi/sign', data)
export const getDevicesApi = (params) => request.get('/system/devices', { params })
export const updateDeviceStatusApi = (id, status) => request.patch(`/system/devices/${id}/status`, { status })
export const deleteDeviceApi = (id) => request.delete(`/system/devices/${id}`)
